<?php
// Variables
return [
  "creatorName" => "Pixinvent",
  "creatorUrl" => "https://pixinvent.com",
  "templateName" => "GiGi | Paack",
  "templateSuffix" => "GiGi | Paack",
  "templateVersion" => "3.0.0",
  "templateFree" => false,
  "templateDescription" => "GiGi | Paack",
  "templateKeyword" => "GiGi | Paack",
  "licenseUrl" => "#",
  "livePreview" => "#",
  "productPage" => "#",
  "support" => "#",
  "moreThemes" => "#",
  "ogTitle" => "GiGi | Paack",
  "ogImage" => "#",
  "ogType" => "Paack",
  "documentation" => "#",
  "generator" => "",
  "changelog" => "#",
  "repository" => "#",
  "gitRepo" => "vuexy-html-laravel-admin-template",
  "gitRepoAccess" => "#",
  "githubFreeUrl" => "#",
  "facebookUrl" => "#",
  "twitterUrl" => "#",
  "githubUrl" => "#",
  "dribbbleUrl" => "#",
  "instagramUrl" => "#"
];
